In [1]:
import pycaret
from pycaret.datasets import get_data

In [2]:
data = get_data('juice')

,Id,Purchase,WeekofPurchase,StoreID,PriceCH,PriceMM,DiscCH,DiscMM,SpecialCH,SpecialMM,LoyalCH,SalePriceMM,SalePriceCH,PriceDiff,Store7,PctDiscMM,PctDiscCH,ListPriceDiff,STORE
0,1,CH,237,1,1.75,1.99,0.00,0.0,0,0,0.500000,1.99,1.75,0.24,No,0.000000,0.000000,0.24,1
1,2,CH,239,1,1.75,1.99,0.00,0.3,0,1,0.600000,1.69,1.75,-0.06,No,0.150754,0.000000,0.24,1
2,3,CH,245,1,1.86,2.09,0.17,0.0,0,0,0.680000,2.09,1.69,0.40,No,0.000000,0.091398,0.23,1
3,4,MM,227,1,1.69,1.69,0.00,0.0,0,0,0.400000,1.69,1.69,0.00,No,0.000000,0.000000,0.00,1
4,5,CH,228,7,1.69,1.69,0.00,0.0,0,0,0.956535,1.69,1.69,0.00,Yes,0.000000,0.000000,0.00,0

In [7]:
import mlflow
from pycaret.classification import *
# disable MLflow logging to avoid 'ThreadLocalVariable' .copy error in this environment
clf1 = setup(data, target='Purchase', session_id=123, log_experiment=False, experiment_name='juice')

In [8]:
best_model = compare_models()

In [9]:
lr=create_model('lr')

In [10]:
lr = create_model('dt')

In [12]:
rf= create_model('rf', fold= 5)

In [13]:
models()

,Name,Reference,Turbo
ID,,,
lr,Logistic Regression,sklearn.linear_model._logistic.LogisticRegression,True
knn,K Neighbors Classifier,sklearn.neighbors._classification.KNeighborsCl...,True
nb,Naive Bayes,sklearn.naive_bayes.GaussianNB,True
dt,Decision Tree Classifier,sklearn.tree._classes.DecisionTreeClassifier,True
svm,SVM - Linear Kernel,sklearn.linear_model._stochastic_gradient.SGDC...,True
rbfsvm,SVM - Radial Kernel,sklearn.svm._classes.SVC,False
gpc,Gaussian Process Classifier,sklearn.gaussian_process._gpc.GaussianProcessC...,False
mlp,MLP Classifier,sklearn.neural_network._multilayer_perceptron....,False
ridge,Ridge Classifier,sklearn.linear_model._ridge.RidgeClassifier,True
rf,Random Forest Classifier,sklearn.ensemble._forest.RandomForestClassifier,True
qda,Quadratic Discriminant Analysis,sklearn.discriminant_analysis.QuadraticDiscrim...,True
ada,Ada Boost Classifier,sklearn.ensemble._weight_boosting.AdaBoostClas...,True
gbc,Gradient Boosting Classifier,sklearn.ensemble._gb.GradientBoostingClassifier,True
lda,Linear Discriminant Analysis,sklearn.discriminant_analysis.LinearDiscrimina...,True
et,Extra Trees Classifier,sklearn.ensemble._forest.ExtraTreesClassifier,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMClassifier,True
dummy,Dummy Classifier,sklearn.dummy.DummyClassifier,True

In [16]:
models(type = 'ensemble').index.tolist()

['rf', 'ada', 'gbc', 'et', 'lightgbm']

In [20]:
ensemble_models = compare_models(include=models(type='ensemble').index.tolist(), fold = 3)

In [21]:
tune_lr = tune_model(lr)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [22]:
bagged_lr = ensemble_model(lr)

In [26]:
lr = create_model('dt')

Initiated  . . . . . . . . . . . . . . . . . .              15:28:52
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

In [27]:
boosted_lr = ensemble_model(lr, method = 'Boosting')

In [29]:
blender = blend_models(estimator_list= [lr, boosted_lr, bagged_lr], method = 'soft')

Initiated  . . . . . . . . . . . . . . . . . .              15:30:50
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

In [30]:
stacker = stack_models(estimator_list= [lr, boosted_lr, bagged_lr], meta_model = rf)

In [38]:
# plot_model(rf)

In [37]:
# plot_model(rf, plot = 'confusion_matrix')

In [36]:
# plot_model(rf, plot = 'pr')

In [41]:
# evaluate_model(rf)

In [48]:
best = automl(optimize = 'Recall')
best

LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)

In [50]:
pred_holdout = predict_model(best)
pred_holdout.head()

,Id,WeekofPurchase,StoreID,PriceCH,PriceMM,DiscCH,DiscMM,SpecialCH,SpecialMM,LoyalCH,...,SalePriceCH,PriceDiff,Store7,PctDiscMM,PctDiscCH,ListPriceDiff,STORE,Purchase,prediction_label,prediction_score
1065,1066,252,7,1.86,2.09,0.10,0.0,0,0,0.587822,...,1.76,0.33,Yes,0.000000,0.053763,0.23,0,CH,CH,0.8574
745,746,233,7,1.75,1.99,0.00,0.4,1,0,0.500000,...,1.75,-0.16,Yes,0.201005,0.000000,0.24,0,CH,MM,0.5164
562,563,230,4,1.79,1.79,0.00,0.0,0,0,0.667200,...,1.79,0.00,No,0.000000,0.000000,0.00,4,CH,CH,0.6695
333,334,236,7,1.75,1.99,0.00,0.4,0,0,0.119538,...,1.75,-0.16,Yes,0.201005,0.000000,0.24,0,MM,MM,0.8869
477,478,266,7,1.86,2.13,0.37,0.0,1,0,0.616000,...,1.49,0.64,Yes,0.000000,0.198925,0.27,0,CH,CH,0.9520

In [51]:
new_data = data.copy()
new_data.drop(['Purchase'], axis=1, inplace=True)
predict_new = predict_model(best, data=new_data)
predict_new.head()

,Id,WeekofPurchase,StoreID,PriceCH,PriceMM,DiscCH,DiscMM,SpecialCH,SpecialMM,LoyalCH,SalePriceMM,SalePriceCH,PriceDiff,Store7,PctDiscMM,PctDiscCH,ListPriceDiff,STORE,prediction_label,prediction_score
0,1,237,1,1.75,1.99,0.00,0.0,0,0,0.500000,1.99,1.75,0.24,No,0.000000,0.000000,0.24,1,CH,0.6296
1,2,239,1,1.75,1.99,0.00,0.3,0,1,0.600000,1.69,1.75,-0.06,No,0.150754,0.000000,0.24,1,CH,0.6131
2,3,245,1,1.86,2.09,0.17,0.0,0,0,0.680000,2.09,1.69,0.40,No,0.000000,0.091398,0.23,1,CH,0.9264
3,4,227,1,1.69,1.69,0.00,0.0,0,0,0.400000,1.69,1.69,0.00,No,0.000000,0.000000,0.00,1,MM,0.7843
4,5,228,7,1.69,1.69,0.00,0.0,0,0,0.956535,1.69,1.69,0.00,Yes,0.000000,0.000000,0.00,0,CH,0.9604

In [57]:
import pandas as pd
import seaborn as sns

In [59]:
data = sns.load_dataset('tips')

In [60]:
data['sex'] = data['sex'].astype('category').cat.codes
data['smoker'] = data['smoker'].astype('category').cat.codes
data['day'] = data['day'].astype('category').cat.codes
data['time'] = data['time'].astype('category').cat.codes

In [61]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size=0.2, random_state=123)

In [65]:
regression_setup = setup(data=train,
    target='tip',
    session_id=123,
    normalize=True,
    polynomial_features=True,
    remove_multicollinearity=True,
    log_experiment=False, # Disable experiment logging
    experiment_name='tips_regression',
    verbose=False )
# Suppress logs)

In [66]:
best_model = compare_models()

In [67]:
print (best_model)

HuberRegressor(alpha=0.0001, epsilon=1.35, fit_intercept=True, max_iter=100,
               tol=1e-05, warm_start=False)

In [68]:
tuned_model = tune_model(best_model, optimize = 'MAE')

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [70]:
evaluate_model(tuned_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [71]:
final_model = finalize_model(tuned_model)
predictions = predict_model(final_model, data=test)

In [74]:
from  sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
true_values= test['tip']
print (predictions.columns)

Index(['total_bill', 'sex', 'smoker', 'day', 'time', 'size', 'tip',
       'prediction_label'],
      dtype='object')

In [76]:
predicted_values = predictions['prediction_label']

In [77]:
mse = mean_squared_error(true_values, predicted_values)
r2 = r2_score(true_values, predicted_values)
print("Mean Squared Error: {mse}".format(mse=mse))
print("R-squared: {r2}".format(r2=r2))

Mean Squared Error: 0.5065152826390726
R-squared: 0.42934574609682163